default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bonzo
  password: postgres

development:
  <<: *default
  database: wantedly_development
test:
  <<: *default
  database: wantedly_test

production:
  <<: *default
  database: wantedly_production
  username: wantedly
  password: <%= ENV['WANTEDLY_DATABASE_PASSWORD'] %>
